#!/bin/bash
#Configuration
cfiles=(wrapper)
finalcfile=main
libname=prog
mlfiles=(prog)
mlifiles=(prog)
mllibs=(unix bigarray)
ocamlfind=ocamlfind
ocamlfind_packs=(cpdf)
stubs=(camlpdf)

#Script
ranlib=`ocamlc -config 2>/dev/null | grep ranlib | sed 's/ranlib: //'`
native_c_libraries=`ocamlc -config 2>/dev/null | grep native_c_libraries | sed 's/native_c_libraries: //'`
libdir=`ocamlc -where`
uname=`uname -s`
if [ "${uname:0:6}" == "CYGWIN" ];then	
libdir=`echo $libdir | dos2unix`
libdir=`cygpath $libdir`
link="flexlink -chain mingw -exe"
exesuffix=".exe"
else
link="cc"
exesuffix=""
fi
camllibs=$(printf "%s.cmxa " "${mllibs[@]}")
camlcmx=$(printf "%s.cmx " "${mlfiles[@]}")
camllink=$(printf -- "-l%s " "${mllibs[@]}")
camlpackages=$(printf -- "-package %s " "${ocamlfind_packs[@]}")
camlpackcmxa=$(printf "%s.cmxa " "${ocamlfind_packs[@]}")
for x in "${mlifiles[@]}"
do
$ocamlfind ocamlc $camlpackages ${x}.mli
done
for x in "${mlfiles[@]}"
do
$ocamlfind ocamlopt $camlpackages -c ${x}.ml
done
$ocamlfind ocamlopt $camlpackages -output-obj -o impl.o $camllibs $camlpackcmxa $camlcmx
for x in "${cfiles[@]}"
do
$ocamlfind ocamlc -c ${x}.c
done
rm -rf lib${libname}.a
ar rc lib${libname}.a impl.o
mkdir -p tmp_asmrun
asmrun_members=$(ar t ${libdir}/libasmrun.a | grep -v '__.*')
for stub in $stubs
do
if [ "${uname:0:6}" == "CYGWIN" ];then	
thefile=`ocamlfind query ${stub} | dos2unix`
thefile=`cygpath $thefile`
else
thefile=`ocamlfind query ${stub}`
fi
therest="/lib${stub}_stubs.a"
stub_members=$(ar t ${thefile}${therest} | grep -v '__.*')
( cd tmp_asmrun && ar x ${thefile}${therest} )
for mem in $stub_members; do ar rc lib${libname}.a tmp_asmrun/$mem; done
done
( cd tmp_asmrun && ar x ${libdir}/libasmrun.a )
for mem in $asmrun_members; do ar rc lib${libname}.a tmp_asmrun/$mem; done
for x in "${cfiles[o]}"
do
ar rc lib${libname}.a ${x}.o 
done
$ranlib lib${libname}.a
rm -rf tmp_asmrun
$ocamlfind ocamlc -c ${finalcfile}.c
linkflags="-L. -l$libname -L$libdir $camllink $native_c_libraries"
echo "LINKER:"$link
echo "FLAGS:"$linkflags
$link -o $finalcfile$exesuffix ${finalcfile}.o $linkflags
