#!/bin/bash
#Configuration
cfiles=(wrapper)
finalcfile=main
libname=prog
mlfiles=(prog)
mlifiles=(prog)
mllibs=(unix bigarray)
ocamlfind=ocamlfind
ocamlfind_packs=(cpdf)
stubs=(camlpdf)

source build
