#!/bin/bash

#Files (.c) making up the C wrapper
cfiles=(wrapper)

#The .c file we'll use to build example executables.
finalcfile=main

#For, say, 'x', we will build libx.a and possibly libx.dll
libname=prog

#The .ml files making up the OCaml code
mlfiles=(prog)

#The .mli files making up the OCaml code
mlifiles=(prog)

#Libraries from the OCaml distribution required by this code
mllibs=(unix bigarray)

#How to call ocamlfind
ocamlfind=ocamlfind

#OCamlfind packages required to build the OCaml code
ocamlfind_packs=()

#OCamlfind packages in ocamlfind_packs or required by anything in
#ocamlfind_packs which have stubs because they themselves contain C code.
stubs=()

source generic
